# -*- coding: utf-8 -*-
"""BTL_Mon_PTDLL_Nhom8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11du3JbL1pEt6VqjYFgNIZ7en7kq7bvz-

## **1.Nhiệt Độ của Chim Cánh cụt**
"""

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

temps = 38 + np.random.randn(100) * 0.5
x = [x for x in range(len(temps))]

fig = plt.figure(figsize=(4, 3), facecolor='w')
plt.plot(x, temps, '-')
plt.fill_between(x, temps, 37, where=(temps > 37), facecolor='g', alpha=0.6)
plt.title("Body Temperature of Penguins (~38°C)", fontsize=10)

data = io.BytesIO()
plt.savefig(data)
image = f"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Penguin Body Temperature Visualization"
display.display(display.Markdown(f"""![{alt}]({image})"""))
plt.close(fig)

"""## **2. Nhiệt Độ Cơ Thể Từng Loài Chim Cánh Cụt**"""

# 1. Nhập các thư viện cần thiết
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 2. Tải dữ liệu chim cánh cụt
du_lieu_chim = sns.load_dataset("penguins")

# 3. Làm sạch dữ liệu
du_lieu_chim = du_lieu_chim.dropna()

# 4. Tạo dữ liệu nhiệt độ cơ thể giả lập
np.random.seed(42)
du_lieu_chim["Nhiet_do_co_the"] = np.random.normal(38, 0.5, len(du_lieu_chim))

# 5. Thống kê nhiệt độ cơ thể
print("Thống kê nhiệt độ cơ thể chim cánh cụt")
print("Trung bình:", round(du_lieu_chim["Nhiet_do_co_the"].mean(),2),"°C")
print("Nhỏ nhất:", round(du_lieu_chim["Nhiet_do_co_the"].min(),2),"°C")
print("Lớn nhất:", round(du_lieu_chim["Nhiet_do_co_the"].max(),2),"°C")

# 6. Tính nhiệt độ trung bình theo loài
nhiet_do_theo_loai = du_lieu_chim.groupby("species")["Nhiet_do_co_the"].mean()

print("\nNhiệt độ cơ thể trung bình theo loài:")
print(nhiet_do_theo_loai)

# 7. Vẽ biểu đồ
plt.figure(figsize=(8,5))

mau_sac = ["#6A5ACD", "#20B2AA", "#FF8C00"]

cot = plt.bar(nhiet_do_theo_loai.index, nhiet_do_theo_loai.values, color=mau_sac)

# Hiển thị giá trị trên cột
for c in cot:
    y = c.get_height()
    plt.text(
        c.get_x()+c.get_width()/2,
        y+0.02,
        round(y,2),
        ha='center'
    )

plt.title("Nhiệt độ cơ thể trung bình của các loài chim cánh cụt")
plt.xlabel("Loài chim cánh cụt")
plt.ylabel("Nhiệt độ cơ thể (°C)")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

"""## **3. Nhiệt Độ Môi Trường Sống của Chim Cánh Cụt**"""

# 1. Nhập các thư viện cần thiết
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# 2. Tải dữ liệu chim cánh cụt
du_lieu_chim = sns.load_dataset("penguins")

# 3. Làm sạch dữ liệu (loại bỏ giá trị bị thiếu)
du_lieu_chim = du_lieu_chim.dropna()

# 4. Tạo dữ liệu nhiệt độ môi trường theo từng đảo
nhiet_do_dao = {
    "Torgersen": -2,
    "Biscoe": 1,
    "Dream": -1
}

# Thêm cột nhiệt độ vào bảng dữ liệu
du_lieu_chim["Nhiet_do_C"] = du_lieu_chim["island"].map(nhiet_do_dao)
+ np.random.normal(0,1,len(du_lieu_chim))

# 5. Thống kê nhiệt độ
print("Thống kê nhiệt độ môi trường của chim cánh cụt")
print("Trung bình:", round(du_lieu_chim["Nhiet_do_C"].mean(),2),"°C")
print("Nhỏ nhất:", round(du_lieu_chim["Nhiet_do_C"].min(),2),"°C")
print("Lớn nhất:", round(du_lieu_chim["Nhiet_do_C"].max(),2),"°C")

# 6. Tính nhiệt độ trung bình theo đảo
nhiet_do_trung_binh = du_lieu_chim.groupby("island")["Nhiet_do_C"].mean()

print("\nNhiệt độ trung bình theo đảo:")
print(nhiet_do_trung_binh)

# 7. Vẽ biểu đồ
plt.figure(figsize=(8,5))

mau_sac = ["#4C72B0", "#55A868", "#C44E52"]

cot = plt.bar(nhiet_do_trung_binh.index, nhiet_do_trung_binh.values,
              color=mau_sac)

# Đổi tên hiển thị trục X
plt.xticks(
    ["Torgersen","Biscoe","Dream"],
    ["Biển lạnh","Băng tuyết","Biển bờ đá"]
)

# Hiển thị giá trị trên mỗi cột
for c in cot:
    y = c.get_height()
    plt.text(
        c.get_x()+c.get_width()/2,
        y+0.05,
        round(y,2),
        ha='center'
    )

plt.title("Nhiệt độ môi trường sống của chim cánh cụt")
plt.xlabel("Môi trường sống")
plt.ylabel("Nhiệt độ (°C)")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

"""## **4. Thức ăn của Chim Cánh Cụt**"""

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

# Dữ liệu giả lập về thức ăn của chim cánh cụt
foods = ["Cá", "Krill", "Mực"]
food_percent = [50, 35, 15]

# Dữ liệu về môi trường sống
habitats = ["Biển lạnh", "Băng tuyết", "Bờ biển đá"]
habitat_percent = [60, 25, 15]

fig = plt.figure(figsize=(8,4), facecolor='white')


plt.subplot(1,2,1)
colors_food = ["#6A5ACD", "#FF8C00", "#20B2AA"]  # màu lạ
plt.pie(food_percent, labels=foods, autopct='%1.0f%%', colors=colors_food,
        startangle=90)
plt.title("Thức ăn của chim cánh cụt")


plt.tight_layout()

data = io.BytesIO()
plt.savefig(data)
image = f"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Phân tích chim cánh cụt"
display.display(display.Markdown(f"""![{alt}]({image})"""))
plt.close(fig)

"""## **5. Các bộ phận của Chim**"""

import seaborn as sns
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

# Tải dữ liệu chim cánh cụt
penguins = sns.load_dataset("penguins")

# Tính giá trị trung bình của các bộ phận
dac_diem = {
    "Độ dài mỏ (mm)": penguins["bill_length_mm"].mean(),
    "Độ dày mỏ (mm)": penguins["bill_depth_mm"].mean(),
    "Độ dài cánh (mm)": penguins["flipper_length_mm"].mean(),
    "KL cơ thể (g)": penguins["body_mass_g"].mean()
}

labels = list(dac_diem.keys())
values = list(dac_diem.values())

fig = plt.figure(figsize=(6,4), facecolor='w')

plt.bar(labels, values)
plt.title("Các đặc điểm cơ thể của chim cánh cụt", fontsize=11)
plt.xlabel("Bộ phận cơ thể")
plt.ylabel("Giá trị trung bình")
plt.xticks(rotation=20)
plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()   # giúp không bị mất chữ

data = io.BytesIO()
plt.savefig(data, bbox_inches='tight')  # tránh cắt chữ
image = f"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Biểu đồ đặc điểm chim cánh cụt"
display.display(display.Markdown(f"""![{alt}]({image})"""))
plt.close(fig)

"""## **6. Tuổi Thọ Của Chim Cánh Cụt**"""

import matplotlib.pyplot as plt
import IPython.display as display
import io
import base64

# Dữ liệu tuổi thọ trung bình (năm)
loai_chim = [
    "Chim cánh cụt Adelie",
    "Chim cánh cụt Chinstrap",
    "Chim cánh cụt Gentoo"

]

tuoi_tho = [15, 18, 17]

fig = plt.figure(figsize=(6,4), facecolor='white')

mau_sac = ["#6A5ACD", "#20B2AA", "#FF8C00"]

plt.bar(loai_chim, tuoi_tho, color=mau_sac)

plt.title("Tuổi thọ trung bình của các loài chim cánh cụt")
plt.xlabel("Loài chim cánh cụt")
plt.ylabel("Tuổi thọ trung bình (năm)")
plt.xticks(rotation=20)

plt.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()

data = io.BytesIO()
plt.savefig(data, bbox_inches='tight')
image = f"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Biểu đồ tuổi thọ chim cánh cụt"
display.display(display.Markdown(f"""![{alt}]({image})"""))
plt.close(fig)

"""## **7. Độ Dày Mỏ của Chim**"""

# 1. Import thư viện
import seaborn as sns
import matplotlib.pyplot as plt

# 2. Tải dữ liệu chim cánh cụt
penguins = sns.load_dataset("penguins")

# 3. Làm sạch dữ liệu
penguins = penguins.dropna()

# 4. Lấy dữ liệu độ dày mỏ
bill_depth = penguins["bill_depth_mm"]

# 5. Thống kê cơ bản
print("Thống kê độ dày mỏ chim cánh cụt")
print("Trung bình:", bill_depth.mean())
print("Nhỏ nhất:", bill_depth.min())
print("Lớn nhất:", bill_depth.max())

# 6. Tính trung bình theo từng loài
bill_depth_species = penguins.groupby("species")["bill_depth_mm"].mean()
print("\nĐộ dày mỏ trung bình theo loài:")
print(bill_depth_species)

# 7. Vẽ biểu đồ
plt.figure(figsize=(6,4))

plt.bar(bill_depth_species.index, bill_depth_species.values)

plt.title("Độ dày mỏ trung bình của các loài chim cánh cụt")
plt.xlabel("Loài chim cánh cụt")
plt.ylabel("Độ dày mỏ (mm)")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

"""## **8.  Giới Tinh của Chim Cánh Cụt**"""

import seaborn as sns
import matplotlib.pyplot as plt
import IPython.display as display
import io
import base64

# Tải dữ liệu chim cánh cụt
penguins = sns.load_dataset("penguins")

# Đổi giới tính sang tiếng Việt
penguins["Giới_tính"] = penguins["sex"].map({
    "Male": "Con đực",
    "Female": "Con cái"
})

# Tạo figure
fig = plt.figure(figsize=(6,4), facecolor='white')

# Vẽ biểu đồ violin
sns.violinplot(
    data=penguins,
    x="Giới_tính",
    y="body_mass_g",
    palette=["#6A5ACD", "#FF69B4"]
)

plt.xlabel("Giới tính")
plt.ylabel("Khối lượng cơ thể (gram)")
plt.title("Phân bố khối lượng cơ thể chim cánh cụt theo giới tính")

plt.tight_layout()

data = io.BytesIO()
plt.savefig(data, bbox_inches='tight')

image = f"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Biểu đồ khối lượng cơ thể chim cánh cụt"

display.display(display.Markdown(f"""![{alt}]({image})"""))

plt.close(fig)



"""## **9. Chiều Dài Vây của Chim Cánh Cụt**"""

# 1. Import thư viện
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# 2. Tải dataset chim cánh cụt
penguins = sns.load_dataset("penguins")

# 3. Xem dữ liệu
print("5 dòng dữ liệu đầu:")
print(penguins.head())

# 4. Làm sạch dữ liệu (loại bỏ giá trị thiếu)
penguins = penguins.dropna()

# 5. Lấy dữ liệu chiều dài vây
flipper_length = penguins["flipper_length_mm"]

# 6. Thống kê cơ bản
print("\nThống kê chiều dài vây của chim cánh cụt")
print("Chiều dài trung bình:", flipper_length.mean())
print("Chiều dài nhỏ nhất:", flipper_length.min())
print("Chiều dài lớn nhất:", flipper_length.max())
print("Độ lệch chuẩn:", flipper_length.std())

# 7. Tính chiều dài vây trung bình theo loài
flipper_by_species = penguins.groupby("species")["flipper_length_mm"].mean()
print("\nChiều dài vây trung bình theo loài:")
print(flipper_by_species)

# 8. Vẽ biểu đồ histogram
plt.figure(figsize=(6,4))
plt.hist(flipper_length, bins=20, color="#20B2AA", edgecolor="black")

plt.title("chiều dài vây của chim cánh cụt")
plt.xlabel("Chiều dài vây (mm)")
plt.ylabel("Số lượng")

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()

"""##  10.Lớp mỡ và Độ Dày Lông Của Chim Cánh Cụt"""

# 1. Nhập thư viện
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# 2. Tải dữ liệu chim cánh cụt
du_lieu = sns.load_dataset("penguins")

# 3. Làm sạch dữ liệu
du_lieu = du_lieu.dropna()

# 4. Tạo dữ liệu mô phỏng lớp mỡ và độ dày lông
np.random.seed(1)

du_lieu["Lop_mo_cm"] = np.random.normal(3.5, 0.6, len(du_lieu))
du_lieu["Do_day_long_mm"] = np.random.normal(25, 3, len(du_lieu))

# 5. Thống kê dữ liệu
print("THỐNG KÊ LỚP MỠ CHIM CÁNH CỤT")
print("Trung bình:", round(du_lieu["Lop_mo_cm"].mean(),2), "cm")
print("Nhỏ nhất:", round(du_lieu["Lop_mo_cm"].min(),2), "cm")
print("Lớn nhất:", round(du_lieu["Lop_mo_cm"].max(),2), "cm")

print("\nTHỐNG KÊ ĐỘ DÀY LÔNG")
print("Trung bình:", round(du_lieu["Do_day_long_mm"].mean(),2), "mm")
print("Nhỏ nhất:", round(du_lieu["Do_day_long_mm"].min(),2), "mm")
print("Lớn nhất:", round(du_lieu["Do_day_long_mm"].max(),2), "mm")

# 6. Tính trung bình theo loài
trung_binh = du_lieu.groupby("species")[["Lop_mo_cm","Do_day_long_mm"]].mean()

print("\nTrung bình theo loài:")
print(trung_binh)

# 7. Vẽ biểu đồ so sánh
plt.figure(figsize=(8,5))

x = np.arange(len(trung_binh.index))
width = 0.35

plt.bar(x - width/2, trung_binh["Lop_mo_cm"], width,
        label="Lớp mỡ (cm)", color="#4C72B0")

plt.bar(x + width/2, trung_binh["Do_day_long_mm"], width,
        label="Độ dày lông (mm)", color="#55A868")

plt.xticks(x, trung_binh.index)

plt.title("So sánh lớp mỡ và độ dày lông của các loài chim cánh cụt")
plt.xlabel("Loài chim cánh cụt")
plt.ylabel("Giá trị")

plt.legend()

plt.grid(axis="y", linestyle="--", alpha=0.5)

plt.tight_layout()
plt.show()